### ISSUE TITLE
Crash on Start: Unable to get provider com.huawei.hms.update.provider.UpdateProvider

### ISSUE THREAD

**Issue by Migueton** [EvilMindDevs/hms-unity-plugin#368]
Hello, I am having an exception when I start the game in my Huawei. I just updated Unity 2021.3.10f1 and your plugin to 2.2.5. I have tried to follow other threads' solutions like [this one](https://github.com/EvilMindDevs/hms-unity-plugin/issues/350) but didn't have any luck.  Any idea why could not find the provider?

> 2022-10-04 13:51:28.169 25243-25243/? E/AndroidRuntime: FATAL EXCEPTION: main
>     Process: com.youdagames.gop3multiplayer.huawei, PID: 25243
>     java.lang.RuntimeException: Unable to get provider com.huawei.hms.update.provider.UpdateProvider: java.lang.ClassNotFoundException: Didn’t find class “com.huawei.hms.update.provider.UpdateProvider” on path: DexPathList[[zip file “/data/app/com.youdagames.gop3multiplayer.huawei-1/base.apk”],nativeLibraryDirectories=[/data/app/com.youdagames.gop3multiplayer.huawei-1/lib/arm64, /data/app/com.youdagames.gop3multiplayer.huawei-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64, /system/vendor/lib64, /product/lib64]]
>         at android.app.ActivityThread.installProvider(ActivityThread.java:6260)
>         at android.app.ActivityThread.installContentProviders(ActivityThread.java:5775)
>         at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5693)
>         at android.app.ActivityThread.-wrap2(ActivityThread.java)
>         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1637)
>         at android.os.Handler.dispatchMessage(Handler.java:105)
>         at android.os.Looper.loop(Looper.java:156)
>         at android.app.ActivityThread.main(ActivityThread.java:6577)
>         at java.lang.reflect.Method.invoke(Native Method)
>         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:942)
>         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:832)
>      Caused by: java.lang.ClassNotFoundException: Didn’t find class “com.huawei.hms.update.provider.UpdateProvider” on path: DexPathList[[zip file “/data/app/com.youdagames.gop3multiplayer.huawei-1/base.apk”],nativeLibraryDirectories=[/data/app/com.youdagames.gop3multiplayer.huawei-1/lib/arm64, /data/app/com.youdagames.gop3multiplayer.huawei-1/base.apk!/lib/arm64-v8a, /system/lib64, /vendor/lib64, /system/vendor/lib64, /product/lib64]]
>         at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
>         at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
>         at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
>         at android.app.ActivityThread.installProvider(ActivityThread.java:6245)
>         at android.app.ActivityThread.installContentProviders(ActivityThread.java:5775)
>         at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5693)
>         at android.app.ActivityThread.-wrap2(ActivityThread.java)
>         at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1637)
>         at android.os.Handler.dispatchMessage(Handler.java:105)
>         at android.os.Looper.loop(Looper.java:156)
>         at android.app.ActivityThread.main(ActivityThread.java:6577)

**Comment by Migueton** [comment]
Thanks, I am going to check with your settings 

My current settings are:
Min API -> 22
Target -> 30

And yes, we are using several plugins. Some of them that could be conflicting perhaps are Firebase 9.4.0 and Bugsnag 7.2

**Comment by Migueton** [comment]
The Min API set to 26 worked removed that exception, but is a big leap. Is there another way to fix this and keep continuing using Min API 22?

**Comment by alihan98ersoy** [comment]
Did you disable the app combat, maybe this can solve your problem. And our plugin requires min 21 API. With 22 should be working.

**Comment by Migueton** [comment]
enabling or disabling app combat doesn't change it. I still get "Unable to get provider com.huawei.hms.update.provider.UpdateProvider" on both cases.

**Comment by Migueton** [comment]
Ok, we got it sorted. We had in our manifest for a really long time these providers for Huawei, we included them once to fix an issue. At some point the official guidelines for upgrading the plugin have them removed.  Removing these providers from our manifest fixed the issue. Thanks for the help.

        <provider android:name="com.huawei.hms.update.provider.UpdateProvider"
                  android:authorities="${applicationId}.hms.update.provider"
                  android:exported="false"
                  android:grantUriPermissions="true"/>
        <provider
            android:name="com.huawei.updatesdk.fileprovider.UpdateSdkFileProvider"
            android:authorities="${applicationId}.updateSdk.fileProvider"
            android:exported="false"
            android:grantUriPermissions="true">
        </provider>

**Comment by alihan98ersoy** [comment]
Thank you for your interest in our project. You may give us a star to support us and follow up on the project. You can also join our discord channel to follow changes and ask any kind of question about the plugin, gaming ecosystem, etc. You may access it from here: https://discord.io/hmsunityplugin
Thank you and stay tuned!
